# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\"&\n\x0f\x43lassifyRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\")\n\x10\x43lassifyResponse\x12\x15\n\rclassified_as\x18\x01 \x01(\t\"j\n\x13PredictRequirements\x12\x13\n\x0b\x63pu_threads\x18\x01 \x01(\x01\x12\x11\n\tdisk_iops\x18\x02 \x01(\x01\x12\x19\n\x11network_bandwidth\x18\x03 \x01(\x01\x12\x10\n\x08ram_size\x18\x04 \x01(\x01\"t\n\x0ePredictRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x03(\t\x12\x19\n\x11\x61vailability_zone\x18\x04 \x01(\t\x12\x12\n\nallocation\x18\x05 \x01(\t\"=\n\x0fPredictResponse\x12*\n\x0crequirements\x18\x01 \x03(\x0b\x32\x14.PredictRequirements\"\x1a\n\x18RefreshClassifierRequest\"\x1b\n\x19RefreshClassifierResponse\"\x19\n\x17RefreshPredictorRequest\"\x1a\n\x18RefreshPredictorResponse\"\x19\n\x17RefreshInstancesRequest\"\x1a\n\x18RefreshInstancesResponse\"4\n\x10WorkloadCategory\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nparameters\x18\x02 \x03(\t\"\x1c\n\x1aWorkloadsCategoriesRequest\"N\n\x1bWorkloadsCategoriesResponse\x12/\n\x14workloads_categories\x18\x01 \x03(\x0b\x32\x11.WorkloadCategory2\xa0\x03\n\x03\x41pi\x12\x31\n\x08\x43lassify\x12\x10.ClassifyRequest\x1a\x11.ClassifyResponse\"\x00\x12.\n\x07Predict\x12\x0f.PredictRequest\x1a\x10.PredictResponse\"\x00\x12L\n\x11RefreshClassifier\x12\x19.RefreshClassifierRequest\x1a\x1a.RefreshClassifierResponse\"\x00\x12I\n\x10RefreshPredictor\x12\x18.RefreshPredictorRequest\x1a\x19.RefreshPredictorResponse\"\x00\x12I\n\x10RefreshInstances\x12\x18.RefreshInstancesRequest\x1a\x19.RefreshInstancesResponse\"\x00\x12R\n\x13WorkloadsCategories\x12\x1b.WorkloadsCategoriesRequest\x1a\x1c.WorkloadsCategoriesResponse\"\x00\x62\x06proto3')
)




_CLASSIFYREQUEST = _descriptor.Descriptor(
  name='ClassifyRequest',
  full_name='ClassifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='ClassifyRequest.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=51,
)


_CLASSIFYRESPONSE = _descriptor.Descriptor(
  name='ClassifyResponse',
  full_name='ClassifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classified_as', full_name='ClassifyResponse.classified_as', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=94,
)


_PREDICTREQUIREMENTS = _descriptor.Descriptor(
  name='PredictRequirements',
  full_name='PredictRequirements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu_threads', full_name='PredictRequirements.cpu_threads', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_iops', full_name='PredictRequirements.disk_iops', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network_bandwidth', full_name='PredictRequirements.network_bandwidth', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ram_size', full_name='PredictRequirements.ram_size', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=202,
)


_PREDICTREQUEST = _descriptor.Descriptor(
  name='PredictRequest',
  full_name='PredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='PredictRequest.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='PredictRequest.image', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='PredictRequest.parameters', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='availability_zone', full_name='PredictRequest.availability_zone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allocation', full_name='PredictRequest.allocation', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=320,
)


_PREDICTRESPONSE = _descriptor.Descriptor(
  name='PredictResponse',
  full_name='PredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requirements', full_name='PredictResponse.requirements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=383,
)


_REFRESHCLASSIFIERREQUEST = _descriptor.Descriptor(
  name='RefreshClassifierRequest',
  full_name='RefreshClassifierRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=411,
)


_REFRESHCLASSIFIERRESPONSE = _descriptor.Descriptor(
  name='RefreshClassifierResponse',
  full_name='RefreshClassifierResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=440,
)


_REFRESHPREDICTORREQUEST = _descriptor.Descriptor(
  name='RefreshPredictorRequest',
  full_name='RefreshPredictorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=467,
)


_REFRESHPREDICTORRESPONSE = _descriptor.Descriptor(
  name='RefreshPredictorResponse',
  full_name='RefreshPredictorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=495,
)


_REFRESHINSTANCESREQUEST = _descriptor.Descriptor(
  name='RefreshInstancesRequest',
  full_name='RefreshInstancesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=522,
)


_REFRESHINSTANCESRESPONSE = _descriptor.Descriptor(
  name='RefreshInstancesResponse',
  full_name='RefreshInstancesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=550,
)


_WORKLOADCATEGORY = _descriptor.Descriptor(
  name='WorkloadCategory',
  full_name='WorkloadCategory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='WorkloadCategory.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='WorkloadCategory.parameters', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=604,
)


_WORKLOADSCATEGORIESREQUEST = _descriptor.Descriptor(
  name='WorkloadsCategoriesRequest',
  full_name='WorkloadsCategoriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=606,
  serialized_end=634,
)


_WORKLOADSCATEGORIESRESPONSE = _descriptor.Descriptor(
  name='WorkloadsCategoriesResponse',
  full_name='WorkloadsCategoriesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workloads_categories', full_name='WorkloadsCategoriesResponse.workloads_categories', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=636,
  serialized_end=714,
)

_PREDICTRESPONSE.fields_by_name['requirements'].message_type = _PREDICTREQUIREMENTS
_WORKLOADSCATEGORIESRESPONSE.fields_by_name['workloads_categories'].message_type = _WORKLOADCATEGORY
DESCRIPTOR.message_types_by_name['ClassifyRequest'] = _CLASSIFYREQUEST
DESCRIPTOR.message_types_by_name['ClassifyResponse'] = _CLASSIFYRESPONSE
DESCRIPTOR.message_types_by_name['PredictRequirements'] = _PREDICTREQUIREMENTS
DESCRIPTOR.message_types_by_name['PredictRequest'] = _PREDICTREQUEST
DESCRIPTOR.message_types_by_name['PredictResponse'] = _PREDICTRESPONSE
DESCRIPTOR.message_types_by_name['RefreshClassifierRequest'] = _REFRESHCLASSIFIERREQUEST
DESCRIPTOR.message_types_by_name['RefreshClassifierResponse'] = _REFRESHCLASSIFIERRESPONSE
DESCRIPTOR.message_types_by_name['RefreshPredictorRequest'] = _REFRESHPREDICTORREQUEST
DESCRIPTOR.message_types_by_name['RefreshPredictorResponse'] = _REFRESHPREDICTORRESPONSE
DESCRIPTOR.message_types_by_name['RefreshInstancesRequest'] = _REFRESHINSTANCESREQUEST
DESCRIPTOR.message_types_by_name['RefreshInstancesResponse'] = _REFRESHINSTANCESRESPONSE
DESCRIPTOR.message_types_by_name['WorkloadCategory'] = _WORKLOADCATEGORY
DESCRIPTOR.message_types_by_name['WorkloadsCategoriesRequest'] = _WORKLOADSCATEGORIESREQUEST
DESCRIPTOR.message_types_by_name['WorkloadsCategoriesResponse'] = _WORKLOADSCATEGORIESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassifyRequest = _reflection.GeneratedProtocolMessageType('ClassifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:ClassifyRequest)
  ))
_sym_db.RegisterMessage(ClassifyRequest)

ClassifyResponse = _reflection.GeneratedProtocolMessageType('ClassifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:ClassifyResponse)
  ))
_sym_db.RegisterMessage(ClassifyResponse)

PredictRequirements = _reflection.GeneratedProtocolMessageType('PredictRequirements', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTREQUIREMENTS,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:PredictRequirements)
  ))
_sym_db.RegisterMessage(PredictRequirements)

PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:PredictRequest)
  ))
_sym_db.RegisterMessage(PredictRequest)

PredictResponse = _reflection.GeneratedProtocolMessageType('PredictResponse', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:PredictResponse)
  ))
_sym_db.RegisterMessage(PredictResponse)

RefreshClassifierRequest = _reflection.GeneratedProtocolMessageType('RefreshClassifierRequest', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHCLASSIFIERREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:RefreshClassifierRequest)
  ))
_sym_db.RegisterMessage(RefreshClassifierRequest)

RefreshClassifierResponse = _reflection.GeneratedProtocolMessageType('RefreshClassifierResponse', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHCLASSIFIERRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:RefreshClassifierResponse)
  ))
_sym_db.RegisterMessage(RefreshClassifierResponse)

RefreshPredictorRequest = _reflection.GeneratedProtocolMessageType('RefreshPredictorRequest', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHPREDICTORREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:RefreshPredictorRequest)
  ))
_sym_db.RegisterMessage(RefreshPredictorRequest)

RefreshPredictorResponse = _reflection.GeneratedProtocolMessageType('RefreshPredictorResponse', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHPREDICTORRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:RefreshPredictorResponse)
  ))
_sym_db.RegisterMessage(RefreshPredictorResponse)

RefreshInstancesRequest = _reflection.GeneratedProtocolMessageType('RefreshInstancesRequest', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHINSTANCESREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:RefreshInstancesRequest)
  ))
_sym_db.RegisterMessage(RefreshInstancesRequest)

RefreshInstancesResponse = _reflection.GeneratedProtocolMessageType('RefreshInstancesResponse', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHINSTANCESRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:RefreshInstancesResponse)
  ))
_sym_db.RegisterMessage(RefreshInstancesResponse)

WorkloadCategory = _reflection.GeneratedProtocolMessageType('WorkloadCategory', (_message.Message,), dict(
  DESCRIPTOR = _WORKLOADCATEGORY,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:WorkloadCategory)
  ))
_sym_db.RegisterMessage(WorkloadCategory)

WorkloadsCategoriesRequest = _reflection.GeneratedProtocolMessageType('WorkloadsCategoriesRequest', (_message.Message,), dict(
  DESCRIPTOR = _WORKLOADSCATEGORIESREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:WorkloadsCategoriesRequest)
  ))
_sym_db.RegisterMessage(WorkloadsCategoriesRequest)

WorkloadsCategoriesResponse = _reflection.GeneratedProtocolMessageType('WorkloadsCategoriesResponse', (_message.Message,), dict(
  DESCRIPTOR = _WORKLOADSCATEGORIESRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:WorkloadsCategoriesResponse)
  ))
_sym_db.RegisterMessage(WorkloadsCategoriesResponse)



_API = _descriptor.ServiceDescriptor(
  name='Api',
  full_name='Api',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=717,
  serialized_end=1133,
  methods=[
  _descriptor.MethodDescriptor(
    name='Classify',
    full_name='Api.Classify',
    index=0,
    containing_service=None,
    input_type=_CLASSIFYREQUEST,
    output_type=_CLASSIFYRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='Api.Predict',
    index=1,
    containing_service=None,
    input_type=_PREDICTREQUEST,
    output_type=_PREDICTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RefreshClassifier',
    full_name='Api.RefreshClassifier',
    index=2,
    containing_service=None,
    input_type=_REFRESHCLASSIFIERREQUEST,
    output_type=_REFRESHCLASSIFIERRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RefreshPredictor',
    full_name='Api.RefreshPredictor',
    index=3,
    containing_service=None,
    input_type=_REFRESHPREDICTORREQUEST,
    output_type=_REFRESHPREDICTORRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RefreshInstances',
    full_name='Api.RefreshInstances',
    index=4,
    containing_service=None,
    input_type=_REFRESHINSTANCESREQUEST,
    output_type=_REFRESHINSTANCESRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WorkloadsCategories',
    full_name='Api.WorkloadsCategories',
    index=5,
    containing_service=None,
    input_type=_WORKLOADSCATEGORIESREQUEST,
    output_type=_WORKLOADSCATEGORIESRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['Api'] = _API

# @@protoc_insertion_point(module_scope)
