workloads:
  # supported categories of workloads
  categories:
    - name: bigdata
      parameters:
        - processors
        - memory
        - data

    - name: caching
      parameters:
        - memory
        - ratio
        - clients

    - name: oltp
      parameters:
        - data
        - clients

    - name: science
      parameters:
        - processors
        - memory

    - name: streaming
      parameters:
        - bitrate
        - clients

    - name: webserving
      parameters:
        - clients



classifier:
  data_generation_level: 1
  partitioning_coefficients: [0.3, 0.35, 0.35]
  minimal_instances_per_category: 80
  default: krico-cpu-48-10-ram-64-40-disk-1780-400

  metrics:
    - 'cpu:time'
    - 'ram:used'
    - 'disk:bandwidth:read'
    - 'disk:bandwidth:write'
    - 'disk:operations:read'
    - 'disk:operations:write'
    - 'network:bandwidth:send'
    - 'network:bandwidth:receive'
    - 'network:packets:send'
    - 'network:packets:receive'
    - 'cpu:cache:misses'
    - 'cpu:cache:references'


predictor:
  load:
    # these two do NOT have to sum up to 100
    percentile: 75
    overhead: 25
