---

# ==================================================================================================================== #
# environment configuration
# ==================================================================================================================== #
environment:
  # base directories, should not be changed
  configuration: /etc/krico
  resources: /var/lib/krico
  logs: /var/log/krico


# ==================================================================================================================== #
# database configuration
# ==================================================================================================================== #
database:
  host: krico-database
  port: 27017


# ==================================================================================================================== #
# OpenStack client configuration
# ==================================================================================================================== #
cloud:
  # Keystone v3 API URL
  endpoint: https://public.fuel.local:5000/v3

  # OpenStack credentials (admin privileges required for creating flavors in the KRICO API service)
  user: admin
  password: admin
  project: admin

  # maximum timeout for operations, in seconds
  timeout: 5


# ==================================================================================================================== #
# number of workers for parallel processing
# ==================================================================================================================== #
processor.threads: 8


# ==================================================================================================================== #
# logger configuration
# ==================================================================================================================== #
logger:
  preset: console

  defaults:
    version: 1

    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

    handlers:
      console:
        class: krico.core.stream.LoggingHandler
        formatter: simple

      file:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        filename: <environment.logs>/default.log

      empty:
        class: logging.NullHandler

    root:
      level: DEBUG

  presets:
    console:
      root:
        handlers: [console]

    file:
      root:
        handlers: [file]

    disabled:
      root:
        handlers: [empty]
