api:
  # bind address for the KRICO API service
  host: 0.0.0.0
  port: 5000

  # API version
  version: 0.2


refresh:
  # how often instance state should be updated, in seconds
  instances: 30

  # how often classifier and predictor models should be updated, in seconds
  models: 3600


predictor:
  reserved:
    vcpus: 0.0    # portion of VCPUs reserved for host OS [0.0 - 1.0]
    ram: 0.1      # portion of RAM reserved for host OS [0.0 - 1.0]
    disk: 0.55    # portion of disk space reserved for host OS [0.0 - 1.0]


zones.metadata:
  filter_tenant_id: 395e2d61370d4fc8b699c89c95545976
